lew_st_trick:
    resource: "@LewSTBundle/Resources/config/routing/trick.yml"
    prefix:   /

lew_st_category:
    resource: "@LewSTBundle/Resources/config/routing/category.yml"
    prefix:   /category