<?php

namespace Lew\STBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPostsTrick($trick, $page = 1, $limit = 0)
    {
        $qb = $this->createQueryBuilder('p');
        $qb
            ->innerJoin('p.trick', 'trick')
            ->addSelect('trick')
            ->where('trick.slug = :trick')
            ->setParameters(array('trick' => $trick))
            ->setFirstResult(($page-1)*$limit)
            ->orderBy('p.date', 'DESC');
        if($limit > 0 ){
            $qb = $qb->setMaxResults($limit);
        }
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
